"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";
import { Providers } from "@/hooks/providers";
import { UserProvider } from "@/hooks/UserContext";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// export const metadata: Metadata = {
//   title: "MultiPost",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="main"></div>
            <NavBar />
            <main className="app">{children}</main>
          </body>
        </html>
      </UserProvider>
    </Providers>
  );
}
